name: Jar

env:
  basename: jPatternClicker

on:
  workflow_run:
    workflows: [ "Build" ]
    branches: [ "master" ]
    types:
      - completed

jobs:
  make-dev-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set current day in env
        run: echo "today=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: gradlew exec
        run: chmod +x gradlew
      - name: Build jar
        run: ./gradlew jar
      - name: Rename jar
        run: mv build/libs/${{ env.basename }}-*.jar ${{ env.basename }}-${{ env.today }}.jar
      - name: Release dev build # TODO: look into used workflow and see if we can eliminate the warning
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.RELEASE }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Development Build"
          files: |
            ${{ env.basename }}-${{ env.today }}.jar