name: Version release to Github

env:
  basename: jPatternClicker

on:
  push:
    tags:
      - "*.*.*"

jobs:
  make-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: gradlew exec
        run: chmod +x gradlew
      - name: Build jar
        run: ./gradlew jar
      - name: Rename jar
        run: mv build/libs/{{ env.basename }}-*.jar ${{ env.basename }}-${{ github.ref_name  }}.jar
      - name: Github Release
        uses: softprops/action-gh-release@v2.2.1
        if: github.ref_type == 'tag'
        with:
          files: |
            ${{ env.basename }}-${{ env.today }}.jar
          token: ${{ secrets.RELEASE }}